workflows:
  ios_workflow:
    name: Build iOS App
    instance_type: mac_pro
    environment:
      vars:
        IOS_DEPLOYMENT_TARGET: '13.0'
    scripts:
      - name: Generate missing iOS files if needed
        script: flutter create .
      - name: Update iOS deployment target in Podfile
        script: |
          sed -i '' "s/platform :ios, '12.0'/platform :ios, '${IOS_DEPLOYMENT_TARGET}'/g" ios/Podfile || true
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS app
        script: flutter build ios --no-codesign
